### ISSUE TITLE
Upgrade to clap version 4.

### ISSUE THREAD

**Issue by ewoolsey** [grantshandy/claui#3]
Not sure if there are any plans to support version 4 of clap, if there are, I would be very interested. If not, feel free to close this issue. Thanks!

**Comment by grantshandy** [comment]
I wasn't aware that there was a new version of clap until just now. I could definitely update this for clap version 4, but it would probably include a rewrite, especially considering some of the poor decisions I made about how this crate works internally.

If this is something you're still interested in I can update it if you'd like.

**Comment by ewoolsey** [comment]
Looking into this more, for my use case I would need to the output of claui to support interactivity via something like [inquire](https://crates.io/crates/inquire). Do you think this would ever be possible? Here is an example program I would like to have work.

```rust
use clap::Command;

fn main() {
    let app = Command::new("Basic");

    claui::run(app, |_| {
        let bool = inquire::Select::new("Select", vec!["This", "That"]).prompt();
        println!("Hello, World!");
    });
}
```

**Comment by synek317** [comment]
Hello, I've been experimenting with this project and since I'm using clap 4, I had to upgrade it in Claui as well. It turned out to be quite easy, at least to do it naively: https://github.com/grantshandy/claui/pull/4

**Comment by grantshandy** [comment]
I've accepted your request for clap4 and I'll be publishing a new version in a few minutes. Sadly, prompts like the ones inquire creates are a little out of the scope of claui, if you want a graphical version of that I think using egui by itself would be a lot more practical.
